# Generated by Django 4.1.13 on 2024-07-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedImage',
        ),
    ]
